CREATE OR REPLACE PROCEDURE "ColruytFMC_PROC"."LKS_DTA_SALESTRANSACTIONS_CUSTOMERS_INCR"()
 RETURNS varchar 
LANGUAGE JAVASCRIPT 

AS $$ 
/*
 __     __          _ _                           _      __  ___  __   __   
 \ \   / /_ _ _   _| | |_ ___ ____   ___  ___  __| |     \ \/ _ \/ /  /_/   
  \ \ / / _` | | | | | __/ __|  _ \ / _ \/ _ \/ _` |      \/ / \ \/ /\      
   \ V / (_| | |_| | | |_\__ \ |_) |  __/  __/ (_| |      / / \/\ \/ /      
    \_/ \__,_|\__,_|_|\__|___/ .__/ \___|\___|\__,_|     /_/ \/_/\__/       
                             |_|                                            

Vaultspeed version: 5.7.2.5, generation date: 2024/11/05 20:06:07
DV_NAME: DVCOL - Release: Four(4) - Comment: add product table - Release date: 2024/11/05 20:02:26, 
BV release: init(1) - Comment: initial release - Release date: 2024/11/05 20:02:44, 
SRC_NAME: TEST_FMC - Release: TEST_FMC(5) - Comment: add table - Release date: 2024/11/05 20:01:30
 */



var truncate_LKS_TEMP_TGT = snowflake.createStatement( {sqlText: `
	TRUNCATE TABLE "TEST_FMC_STG"."LKS_DTA_SALESTRANSACTIONS_CUSTOMERS_TMP";
`} ).execute();


var LKS_TEMP_TGT = snowflake.createStatement( {sqlText: `
	INSERT INTO "TEST_FMC_STG"."LKS_DTA_SALESTRANSACTIONS_CUSTOMERS_TMP"(
		 "LNK_SALESTRANSACTIONS_CUSTOMERS_HKEY"
		,"CUSTOMERS_HKEY"
		,"SALES_TRANSACTIONS_HKEY"
		,"LOAD_DATE"
		,"LOAD_CYCLE_ID"
		,"RECORD_TYPE"
		,"SOURCE"
		,"EQUAL"
		,"DELETE_FLAG"
		,"CDC_SIMULATED"
		,"TRANSACTION_ID"
		,"CUSTOMER_NAME"
	)
	WITH "DIST_STG" AS 
	( 
		SELECT 
			  "STG_DIS_SRC"."SALES_TRANSACTIONS_HKEY" AS "SALES_TRANSACTIONS_HKEY"
			, "STG_DIS_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, MIN("STG_DIS_SRC"."LOAD_DATE") AS "MIN_LOAD_TIMESTAMP"
		FROM "TEST_FMC_STG"."SALES_TRANSACTIONS" "STG_DIS_SRC"
		GROUP BY  "STG_DIS_SRC"."SALES_TRANSACTIONS_HKEY",  "STG_DIS_SRC"."LOAD_CYCLE_ID"
	)
	, "TEMP_TABLE_SET" AS 
	( 
		SELECT 
			  "STG_TEMP_SRC"."LNK_SALESTRANSACTIONS_CUSTOMERS_HKEY" AS "LNK_SALESTRANSACTIONS_CUSTOMERS_HKEY"
			, "STG_TEMP_SRC"."CUSTOMERS_HKEY" AS "CUSTOMERS_HKEY"
			, "STG_TEMP_SRC"."SALES_TRANSACTIONS_HKEY" AS "SALES_TRANSACTIONS_HKEY"
			, "STG_TEMP_SRC"."LOAD_DATE" AS "LOAD_DATE"
			, "STG_TEMP_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, TO_TIMESTAMP(NULL, 'DD/MM/YYYY HH24:MI:SS') AS "LOAD_END_DATE"
			, "STG_TEMP_SRC"."RECORD_TYPE" AS "RECORD_TYPE"
			, 'STG' AS "SOURCE"
			, 1 AS "ORIGIN_ID"
			, CASE WHEN "STG_TEMP_SRC"."__$operation" = 'D' THEN CAST('Y' AS VARCHAR(3)) ELSE CAST('N' AS VARCHAR(3)) END AS "DELETE_FLAG"
			, "STG_TEMP_SRC"."CDC_SIMULATED" AS "CDC_SIMULATED"
			, "STG_TEMP_SRC"."TRANSACTION_ID" AS "TRANSACTION_ID"
			, "STG_TEMP_SRC"."CUSTOMER_NAME" AS "CUSTOMER_NAME"
		FROM "TEST_FMC_STG"."SALES_TRANSACTIONS" "STG_TEMP_SRC"
		UNION 
		SELECT 
			  "LKS_SRC"."LNK_SALESTRANSACTIONS_CUSTOMERS_HKEY" AS "LNK_SALESTRANSACTIONS_CUSTOMERS_HKEY"
			, "LNK_SRC"."CUSTOMERS_HKEY" AS "CUSTOMERS_HKEY"
			, "LNK_SRC"."SALES_TRANSACTIONS_HKEY" AS "SALES_TRANSACTIONS_HKEY"
			, "LKS_SRC"."LOAD_DATE" AS "LOAD_DATE"
			, "LKS_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, MAX("LKS_SRC"."LOAD_DATE")OVER(PARTITION BY "LNK_SRC"."SALES_TRANSACTIONS_HKEY") AS "LOAD_END_DATE"
			, 'SAT' AS "RECORD_TYPE"
			, 'LKS' AS "SOURCE"
			, 0 AS "ORIGIN_ID"
			, "LKS_SRC"."DELETE_FLAG" AS "DELETE_FLAG"
			, "LKS_SRC"."CDC_SIMULATED" AS "CDC_SIMULATED"
			, "LKS_SRC"."TRANSACTION_ID" AS "TRANSACTION_ID"
			, "LKS_SRC"."CUSTOMER_NAME" AS "CUSTOMER_NAME"
		FROM "DV_FL"."LKS_DTA_SALESTRANSACTIONS_CUSTOMERS" "LKS_SRC"
		INNER JOIN "DV_FL"."LNK_SALESTRANSACTIONS_CUSTOMERS" "LNK_SRC" ON  "LKS_SRC"."LNK_SALESTRANSACTIONS_CUSTOMERS_HKEY" = "LNK_SRC"."LNK_SALESTRANSACTIONS_CUSTOMERS_HKEY"
		INNER JOIN "DIST_STG" "DIST_STG" ON  "LNK_SRC"."SALES_TRANSACTIONS_HKEY" = "DIST_STG"."SALES_TRANSACTIONS_HKEY"
	)
	SELECT 
		  "TEMP_TABLE_SET"."LNK_SALESTRANSACTIONS_CUSTOMERS_HKEY" AS "LNK_SALESTRANSACTIONS_CUSTOMERS_HKEY"
		, "TEMP_TABLE_SET"."CUSTOMERS_HKEY" AS "CUSTOMERS_HKEY"
		, "TEMP_TABLE_SET"."SALES_TRANSACTIONS_HKEY" AS "SALES_TRANSACTIONS_HKEY"
		, "TEMP_TABLE_SET"."LOAD_DATE" AS "LOAD_DATE"
		, "TEMP_TABLE_SET"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "TEMP_TABLE_SET"."RECORD_TYPE" AS "RECORD_TYPE"
		, "TEMP_TABLE_SET"."SOURCE" AS "SOURCE"
		, CASE WHEN "TEMP_TABLE_SET"."SOURCE" = 'STG' AND "TEMP_TABLE_SET"."DELETE_FLAG"::varchar || "TEMP_TABLE_SET"."CUSTOMERS_HKEY"::varchar =
			LAG( "TEMP_TABLE_SET"."DELETE_FLAG"::varchar || "TEMP_TABLE_SET"."CUSTOMERS_HKEY"::varchar,1)OVER(PARTITION BY "TEMP_TABLE_SET"."SALES_TRANSACTIONS_HKEY" ORDER BY "TEMP_TABLE_SET"."LOAD_DATE","TEMP_TABLE_SET"."ORIGIN_ID")THEN 1 ELSE 0 END AS "EQUAL"
		, "TEMP_TABLE_SET"."DELETE_FLAG" AS "DELETE_FLAG"
		, "TEMP_TABLE_SET"."CDC_SIMULATED" AS "CDC_SIMULATED"
		, "TEMP_TABLE_SET"."TRANSACTION_ID" AS "TRANSACTION_ID"
		, "TEMP_TABLE_SET"."CUSTOMER_NAME" AS "CUSTOMER_NAME"
	FROM "TEMP_TABLE_SET" "TEMP_TABLE_SET"
	WHERE  "TEMP_TABLE_SET"."SOURCE" = 'STG' OR("TEMP_TABLE_SET"."LOAD_DATE" = "TEMP_TABLE_SET"."LOAD_END_DATE" AND "TEMP_TABLE_SET"."SOURCE" = 'LKS')
	;
`} ).execute();

var LKS_INUR_TGT = snowflake.createStatement( {sqlText: `
	INSERT INTO "DV_FL"."LKS_DTA_SALESTRANSACTIONS_CUSTOMERS"(
		 "LNK_SALESTRANSACTIONS_CUSTOMERS_HKEY"
		,"LOAD_DATE"
		,"LOAD_CYCLE_ID"
		,"DELETE_FLAG"
		,"CDC_SIMULATED"
		,"TRANSACTION_ID"
		,"CUSTOMER_NAME"
	)
	SELECT 
		  "LKS_TEMP_SRC_INUR"."LNK_SALESTRANSACTIONS_CUSTOMERS_HKEY" AS "LNK_SALESTRANSACTIONS_CUSTOMERS_HKEY"
		, "LKS_TEMP_SRC_INUR"."LOAD_DATE" AS "LOAD_DATE"
		, "LKS_TEMP_SRC_INUR"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "LKS_TEMP_SRC_INUR"."DELETE_FLAG" AS "DELETE_FLAG"
		, "LKS_TEMP_SRC_INUR"."CDC_SIMULATED" AS "CDC_SIMULATED"
		, "LKS_TEMP_SRC_INUR"."TRANSACTION_ID" AS "TRANSACTION_ID"
		, "LKS_TEMP_SRC_INUR"."CUSTOMER_NAME" AS "CUSTOMER_NAME"
	FROM "TEST_FMC_STG"."LKS_DTA_SALESTRANSACTIONS_CUSTOMERS_TMP" "LKS_TEMP_SRC_INUR"
	WHERE  "LKS_TEMP_SRC_INUR"."SOURCE" = 'STG' AND "LKS_TEMP_SRC_INUR"."EQUAL" = 0
	;
`} ).execute();


return "Done.";$$;
 
 
