/*
 __     __          _ _                           _      __  ___  __   __   
 \ \   / /_ _ _   _| | |_ ___ ____   ___  ___  __| |     \ \/ _ \/ /  /_/   
  \ \ / / _` | | | | | __/ __|  _ \ / _ \/ _ \/ _` |      \/ / \ \/ /\      
   \ V / (_| | |_| | | |_\__ \ |_) |  __/  __/ (_| |      / / \/\ \/ /      
    \_/ \__,_|\__,_|_|\__|___/ .__/ \___|\___|\__,_|     /_/ \/_/\__/       
                             |_|                                            

Vaultspeed version: 5.7.2.5, generation date: 2024/11/05 20:05:51
DV_NAME: DVCOL - Release: Four(4) - Comment: add product table - Release date: 2024/11/05 20:02:26
 */

/* DROP TABLES */

-- START
DROP TABLE IF EXISTS "TEST_FMC_STG"."LKS_DTA_SALESTRANSACTIONS_CUSTOMERS_TMP" 
CASCADE
;
DROP TABLE IF EXISTS "TEST_FMC_STG"."LKS_DTA_SALESTRANSACTIONS_PRODUCTS_TMP" 
CASCADE
;
DROP TABLE IF EXISTS "TEST_FMC_STG"."SAT_DTA_CUSTOMERS_TMP" 
CASCADE
;
DROP TABLE IF EXISTS "TEST_FMC_STG"."SAT_DTA_PRODUCTS_TMP" 
CASCADE
;
DROP TABLE IF EXISTS "TEST_FMC_STG"."SAT_DTA_SALES_TRANSACTIONS_TMP" 
CASCADE
;

-- END


/* CREATE TABLES */

-- START

CREATE   TABLE "TEST_FMC_STG"."SAT_DTA_CUSTOMERS_TMP"
(
    "CUSTOMERS_HKEY" VARCHAR(40) DEFAULT '0' NOT NULL
   ,"LOAD_DATE" TIMESTAMP_NTZ DEFAULT TO_TIMESTAMP('01/01/2999 00:00:00', 'DD/MM/YYYY HH24:MI:SS') NOT NULL
   ,"LOAD_CYCLE_ID" INTEGER DEFAULT -2147483648 NOT NULL
   ,"HASH_DIFF" VARCHAR(40)
   ,"DELETE_FLAG" VARCHAR(3) DEFAULT '0' NOT NULL
   ,"CDC_SIMULATED" TIMESTAMP_NTZ DEFAULT TO_TIMESTAMP('01/01/2999 00:00:00', 'DD/MM/YYYY HH24:MI:SS') NOT NULL
   ,"NAME" VARCHAR
   ,"CITY" VARCHAR
   ,"LICENSE_PLATE" VARCHAR
   ,"EMAIL" VARCHAR
   ,"SOURCE" VARCHAR
   ,"EQUAL" NUMBER
   ,"RECORD_TYPE" VARCHAR
)
;

COMMENT ON TABLE "TEST_FMC_STG"."SAT_DTA_CUSTOMERS_TMP" IS 'DV_NAME: DVCOL - Release: Four(4) - Comment: add product table - Release date: 2024/11/05 20:02:26';


CREATE   TABLE "TEST_FMC_STG"."SAT_DTA_PRODUCTS_TMP"
(
    "PRODUCTS_HKEY" VARCHAR(40) DEFAULT '0' NOT NULL
   ,"LOAD_DATE" TIMESTAMP_NTZ DEFAULT TO_TIMESTAMP('01/01/2999 00:00:00', 'DD/MM/YYYY HH24:MI:SS') NOT NULL
   ,"LOAD_CYCLE_ID" INTEGER DEFAULT -2147483648 NOT NULL
   ,"HASH_DIFF" VARCHAR(40)
   ,"DELETE_FLAG" VARCHAR(3) DEFAULT '0' NOT NULL
   ,"CDC_SIMULATED" TIMESTAMP_NTZ DEFAULT TO_TIMESTAMP('01/01/2999 00:00:00', 'DD/MM/YYYY HH24:MI:SS') NOT NULL
   ,"PRODUCT_ID" VARCHAR
   ,"PRODUCT_NAME" VARCHAR
   ,"CATEGORY" VARCHAR
   ,"BASE_PRICE" INTEGER
   ,"SOURCE" VARCHAR
   ,"EQUAL" NUMBER
   ,"RECORD_TYPE" VARCHAR
)
;

COMMENT ON TABLE "TEST_FMC_STG"."SAT_DTA_PRODUCTS_TMP" IS 'DV_NAME: DVCOL - Release: Four(4) - Comment: add product table - Release date: 2024/11/05 20:02:26';


CREATE   TABLE "TEST_FMC_STG"."SAT_DTA_SALES_TRANSACTIONS_TMP"
(
    "SALES_TRANSACTIONS_HKEY" VARCHAR(40) DEFAULT '0' NOT NULL
   ,"LOAD_DATE" TIMESTAMP_NTZ DEFAULT TO_TIMESTAMP('01/01/2999 00:00:00', 'DD/MM/YYYY HH24:MI:SS') NOT NULL
   ,"LOAD_CYCLE_ID" INTEGER DEFAULT -2147483648 NOT NULL
   ,"HASH_DIFF" VARCHAR(40)
   ,"DELETE_FLAG" VARCHAR(3) DEFAULT '0' NOT NULL
   ,"CDC_SIMULATED" TIMESTAMP_NTZ DEFAULT TO_TIMESTAMP('01/01/2999 00:00:00', 'DD/MM/YYYY HH24:MI:SS') NOT NULL
   ,"TRANSACTION_ID" VARCHAR
   ,"TRANSACTION_DATE" TIMESTAMP_NTZ(9)
   ,"TRANSACTION_AMOUNT" INTEGER
   ,"SOURCE" VARCHAR
   ,"EQUAL" NUMBER
   ,"RECORD_TYPE" VARCHAR
)
;

COMMENT ON TABLE "TEST_FMC_STG"."SAT_DTA_SALES_TRANSACTIONS_TMP" IS 'DV_NAME: DVCOL - Release: Four(4) - Comment: add product table - Release date: 2024/11/05 20:02:26';


CREATE   TABLE "TEST_FMC_STG"."LKS_DTA_SALESTRANSACTIONS_CUSTOMERS_TMP"
(
    "LNK_SALESTRANSACTIONS_CUSTOMERS_HKEY" VARCHAR(40) DEFAULT '0' NOT NULL
   ,"LOAD_DATE" TIMESTAMP_NTZ DEFAULT TO_TIMESTAMP('01/01/2999 00:00:00', 'DD/MM/YYYY HH24:MI:SS') NOT NULL
   ,"LOAD_CYCLE_ID" INTEGER DEFAULT -2147483648 NOT NULL
   ,"DELETE_FLAG" VARCHAR(3) DEFAULT '0' NOT NULL
   ,"CDC_SIMULATED" TIMESTAMP_NTZ DEFAULT TO_TIMESTAMP('01/01/2999 00:00:00', 'DD/MM/YYYY HH24:MI:SS') NOT NULL
   ,"TRANSACTION_ID" VARCHAR
   ,"CUSTOMER_NAME" VARCHAR
   ,"SOURCE" VARCHAR
   ,"EQUAL" NUMBER
   ,"RECORD_TYPE" VARCHAR
   ,"SALES_TRANSACTIONS_HKEY" VARCHAR(40)
   ,"CUSTOMERS_HKEY" VARCHAR(40)
)
;

COMMENT ON TABLE "TEST_FMC_STG"."LKS_DTA_SALESTRANSACTIONS_CUSTOMERS_TMP" IS 'DV_NAME: DVCOL - Release: Four(4) - Comment: add product table - Release date: 2024/11/05 20:02:26';


CREATE   TABLE "TEST_FMC_STG"."LKS_DTA_SALESTRANSACTIONS_PRODUCTS_TMP"
(
    "LNK_SALESTRANSACTIONS_PRODUCTS_HKEY" VARCHAR(40) DEFAULT '0' NOT NULL
   ,"LOAD_DATE" TIMESTAMP_NTZ DEFAULT TO_TIMESTAMP('01/01/2999 00:00:00', 'DD/MM/YYYY HH24:MI:SS') NOT NULL
   ,"LOAD_CYCLE_ID" INTEGER DEFAULT -2147483648 NOT NULL
   ,"DELETE_FLAG" VARCHAR(3) DEFAULT '0' NOT NULL
   ,"CDC_SIMULATED" TIMESTAMP_NTZ DEFAULT TO_TIMESTAMP('01/01/2999 00:00:00', 'DD/MM/YYYY HH24:MI:SS') NOT NULL
   ,"TRANSACTION_ID" VARCHAR
   ,"PRODUCT_ID" VARCHAR
   ,"SOURCE" VARCHAR
   ,"EQUAL" NUMBER
   ,"RECORD_TYPE" VARCHAR
   ,"SALES_TRANSACTIONS_HKEY" VARCHAR(40)
   ,"PRODUCTS_HKEY" VARCHAR(40)
)
;

COMMENT ON TABLE "TEST_FMC_STG"."LKS_DTA_SALESTRANSACTIONS_PRODUCTS_TMP" IS 'DV_NAME: DVCOL - Release: Four(4) - Comment: add product table - Release date: 2024/11/05 20:02:26';


-- END


